Make partitioner configurable and add FixedPartitionsPartitioner
pinterest/singer pull request #163
Opened 2022-02-10 06:23 UTC by kabochya

Allow configs to be passed to the partitioner via `writer.kafka.producerConfig.partitioner.<config>` keys, and add a partitioner that allows fixed number of partitions to be written to (extension of `SinglePartitionPartitioner`)

2022-02-10 17:16 UTC, ambud requested changes

2022-02-10 17:16 UTC, ambud commented on singer/src/main/java/com/pinterest/singer/writer/partitioners/FixedPartitionsPartitioner.java
> +  private final Random random = new Random(System.currentTimeMillis());
Can we change to ThreadLocalRandom?

2022-02-10 17:16 UTC, ambud commented on singer/src/main/java/com/pinterest/singer/writer/partitioners/FixedPartitionsPartitioner.java
> +    if (!partitionMap.containsKey(numOfPartitions)){
Probably worth adding a comment as to why initializations are done?

2022-02-10 17:38 UTC, vahidhashemian commented on singer/src/main/java/com/pinterest/singer/writer/partitioners/FixedPartitionsPartitioner.java
> +    partitionCount = Integer.parseInt(partitionerConfig.getOrDefault(PARTITIONER_PARTITION_COUNT_KEY, "3"));
What's the reasoning for picking `3` as the default? I was thinking maybe we can use `1` as default so it matches the current single partition partitioner. This way we can use this new partitioner as the default for fixed partitioning and deprecate single partition partitioner going forward.

2022-02-12 06:28 UTC, ambud requested changes

2022-02-12 06:28 UTC, ambud commented on singer/src/test/java/com/pinterest/singer/writer/partitioners/TestFixedNumberPartitionPartitioner.java
> +  public void TestFixedPartitionsPartitioner() {
Could you please change it to camel case?

2022-02-14 20:29 UTC, ambud approved these changes

2022-02-14 20:42 UTC, merged